- borsh-derive-internal/src/enum_de.rs
- borsh-derive-internal/src/enum_ser.rs
- borsh-derive-internal/src/struct_de.rs
- borsh-derive-internal/src/struct_ser.rs
- borsh-derive-internal/src/union_de.rs
- borsh-derive-internal/src/union_ser.rs
- borsh-derive/Cargo.toml
- borsh-derive/src/lib.rs
- borsh-schema-derive-internal/src/enum_schema.rs
- borsh-schema-derive-internal/src/helpers.rs
- borsh-schema-derive-internal/src/struct_schema.rs
> fix: Resolved compilation error due to use of private module syn::export

- borsh/src/de/mod.rs
- borsh/src/ser/mod.rs
Fixes: #17
Fixes: #18
Marks `is_u8` unsafe. Ideally we should not let anyone reimplement it at all, but I'm not sure how to do this with Rust.
Q: Should we release it as a patch or minor version?
> Mark is_u8 unsafe

- .github/workflows/rust.yml
- .travis.yml
- borsh/tests/test_de_errors.rs
I'm adding `.github/workflows/rust.yml`, that should configure the github pipeline for borsh.
> feat: Rewrite the CI

- CODEOWNERS
I feel like sdk-rs project is one of the most significant users of borsh *API*s
> add austinabell to code owners

- .github/workflows/rust.yml
To make pipelines better, let's add
```
RUSTFLAGS: '-D warnings'
CARGO_INCREMENTAL: 0
RUST_BACKTRACE: short
```
> feat: Improve `rust.yml` by adding env flags

- .github/workflows/rust.yml
Fixes https://github.com/near/borsh-rs/issues/71
Might be a simple `fetch-tags: true` option soon, see https://github.com/actions/checkout/pull/579
> fix(infra): checkout: set fetch-depth to pull tags

- .github/workflows/rust.yml
Context: https://github.com/near/borsh-rs/runs/4950992069?check_suite_focus=true
Let's hope this works.. 🤞🏽
> fix(infra): push and create release only if a tag is created

- .github/workflows/rust.yml
See https://near.zulipchat.com/#narrow/stream/308449-nearinc.2Fcore-tools/topic/borsh.20publishing/near/270728464
> ci: publish macros crates even without changes

- borsh-schema-derive-internal/Cargo.toml
- borsh-schema-derive-internal/src/enum_schema.rs
- borsh-schema-derive-internal/src/helpers.rs
- borsh-schema-derive-internal/src/struct_schema.rs
> BorshSchema generics: fix deriving for bounds with trailing comma

- borsh/src/de/mod.rs
- borsh/src/schema.rs
- borsh/src/ser/mod.rs
Clippy added new warnings, so fixing to keep changes separate from #104
> fix: new clippy warnings

- borsh-schema-derive-internal/src/enum_schema.rs
- borsh-schema-derive-internal/src/struct_schema.rs
Fixes : #112 
Apply schema on field_types
> chore: apply Schema on field_type

- borsh/src/lib.rs
> doc: create a brief documentation of crate's features

- .github/workflows/rust.yml
- benchmarks/Cargo.toml
- benchmarks/benches/maps_sets_inner_de.rs
- benchmarks/benches/maps_sets_inner_ser.rs
- benchmarks/src/lib.rs
> feat: sets/maps benches for reference point

- borsh-derive-internal/src/enum_de.rs
- borsh-derive-internal/src/enum_ser.rs
- borsh-derive-internal/src/struct_de.rs
- borsh-derive-internal/src/struct_ser.rs
- borsh-schema-derive-internal/src/enum_schema.rs
- borsh-schema-derive-internal/src/helpers.rs
- borsh-schema-derive-internal/src/struct_schema.rs
- borsh/src/de/mod.rs
- borsh/src/lib.rs
- borsh/src/nostd_io.rs
- borsh/src/schema.rs
- borsh/src/schema_helpers.rs
- borsh/src/ser/helpers.rs
- borsh/src/ser/mod.rs
> refactor: introduce `__private` module with macro runtime

- release-plz.toml
Mentioning [release-plz issue](https://github.com/MarcoIeni/release-plz/issues/841) as an example of usage.
> chore: update release-plz.toml with `changelog_include`

- .github/test.sh
- .github/workflows/rust.yml
- borsh/Cargo.toml
- borsh/src/lib.rs
- borsh/tests/smoke.rs
- borsh/tests/test_schema_enums.rs
- borsh/tests/test_schema_nested.rs
- borsh/tests/test_schema_primitives.rs
- borsh/tests/test_schema_recursive.rs
- borsh/tests/test_schema_structs.rs
- borsh/tests/test_schema_tuple.rs
- borsh/tests/test_schema_with.rs
> chore!: declare and rename `schema` feature to be `unstable__` (may break in `1.x` versions)

- borsh/src/schema.rs
- borsh/src/schema/container_ext/max_size.rs
- borsh/tests/test_schema_enums.rs
- borsh/tests/test_schema_nested.rs
- borsh/tests/test_schema_recursive.rs
- borsh/tests/test_schema_structs.rs
- borsh/tests/test_schema_validate.rs
- borsh/tests/test_schema_with.rs
> chore!: rename `"nil"` -> `"()"`, `"string"` -> `"String"`, `"nonzero_u16"` -> `"NonZeroU16"` (`schema::Declaration`)

- docs/migration_guides/v0.9_to_v1.0.0_near_sdk_rs.md
Md file is description of changes within [borsh update in near-sdk-rs](https://github.com/near/near-sdk-rs/pull/1075)
> doc: `near-sdk-rs` migration guide to `1.0.0`

- .github/workflows/rust.yml
- borsh-derive/src/internals/generics.rs
fixes https://github.com/near/borsh-rs/actions/runs/8051625810/job/21989941967 and https://github.com/near/borsh-rs/actions/runs/8051625810/job/21989943537
> ci: fix `test_exhaustive_checks` step + downgrade package for MSRV test

- borsh/Cargo.toml
This PR bumps hashbrown to 0.15.
> chore: bump hashbrown to 0.15

- borsh/docs/rustdoc_include/borsh_crate_top_level.md
> doc: add mention of `indexmap` feature
